# Generated by Django 4.0.3 on 2022-03-25 20:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('area', models.FloatField(blank=True, null=True)),
                ('perimeter', models.FloatField(blank=True, null=True)),
                ('kaek', models.BigIntegerField(blank=True, null=True)),
                ('numfloor', models.IntegerField(blank=True, db_column='numFloor', null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('landuse', models.CharField(blank=True, db_column='landUse', max_length=30, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('roof', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Building',
                'managed': False,
            },
        ),
    ]
