# Generated by Django 4.0.3 on 2022-03-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_building_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'managed': False},
        ),
    ]
