# Generated by Django 4.0.3 on 2022-03-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_building_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={},
        ),
    ]
