# Generated by Django 4.0.3 on 2022-04-06 01:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_building_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('sitecoverage', models.FloatField(blank=True, db_column='siteCoverage', null=True)),
                ('plotratio', models.FloatField(blank=True, db_column='plotRatio', null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('perimeter', models.FloatField(blank=True, null=True)),
                ('centroid_x', models.FloatField(blank=True, null=True)),
                ('centroid_y', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Block',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'managed': False},
        ),
    ]
