# Generated by Django 4.0.3 on 2022-04-07 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_block_alter_building_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'managed': True},
        ),
    ]
