# Generated by Django 4.0.3 on 2022-04-07 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_alter_block_options_alter_building_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'managed': False},
        ),
    ]
